name: coding_challenge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^8.0.0
  flutter_bloc: ^9.0.0
  dio: ^5.9.2
  equatable: ^2.0.8
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:

  generate: true
  uses-material-design: true

  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair_144pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_144pt-SemiBold.ttf
          weight: 600
